const tasks: string[] = ["Wake up",
    "Make the bed",
    "Drink water",
    "Morning exercise",
    "Take a shower",
    "Have breakfast",
    "Check emails",
    "Plan the day",
    "Review calendar",
    "Study TypeScript",
    "Practice JavaScript",
    "Work on backend",
    "Build API endpoints",
    "Test API",
    "Fix bugs",
    "Review code",
    "Work on database",
    "Write SQL queries",
    "Read documentation",
    "Work on personal project",
    "Take a break",
    "Go for a walk",
    "Have lunch",
    "Practice React",
    "Build UI components",
    "Work with APIs",
    "Write unit tests",
    "Commit changes",
    "Push changes to GitHub",
    "Review project progress",
    "Practice DSA",
    "Solve coding problems",
    "Study system design",
    "Learn Node.js",
    "Practice Express.js",
    "Organize files",
    "Clean the workspace",
    "Reply to messages",
    "Read a book",
    "Listen to music",
    "Watch a tutorial",
    "Work on resume",
    "Apply for jobs",
    "Learn something new",
    "Have dinner",
    "Relax",
    "Plan tomorrow",
    "Review today's work",
    "Get ready for bed",
    "Go to sleep"];

export function getTasks() {
    return tasks;
}

export function addTask(task: string) {
    tasks.push(task);
    return task;
}